export { HugeiconsIcon } from "@hugeicons/react";

export {
  ArrowRight01Icon as ArrowRightIcon,
  ArrowLeft01Icon as ArrowLeftIcon,
  ArrowUpRight01Icon as ArrowUpRightIcon,
  ArrowUp01Icon as ArrowUpIcon,
  ArrowDown01Icon as ArrowDownIcon,
  StarIcon,
  Search01Icon as SearchIcon,
  Cancel01Icon as CloseIcon,
  DashboardCircleIcon as MoreIcon,
  Home09Icon as HomeIcon,
  DashboardSquare01Icon as GridIcon,
  Briefcase01Icon as BriefcaseIcon,
  News01Icon as NewsIcon,
  InformationCircleIcon as InfoIcon,
  Mail01Icon as MailIcon,
  Call02Icon as PhoneIcon,
  Location01Icon as LocationIcon,
  Clock01Icon as ClockIcon,
  Tick02Icon as CheckIcon,
  CheckmarkCircle02Icon as CheckCircleIcon,
  QuoteDownIcon as QuoteIcon,
  Loading03Icon as LoaderIcon,
  AlertCircleIcon as AlertIcon,
  File01Icon as FileIcon,
  Layers01Icon as LayersIcon,
  ChartIncreaseIcon as TrendingUpIcon,
  Target01Icon as TargetIcon,
  FavouriteIcon as HeartIcon,
  FlashIcon as ZapIcon,
  UserGroupIcon as UsersIcon,
  SparklesIcon,
  Linkedin01Icon as LinkedinIcon,
  NewTwitterIcon as TwitterIcon,
  InstagramIcon,
  Facebook01Icon as FacebookIcon,
  YoutubeIcon,
  Megaphone01Icon as MegaphoneIcon,
  SmartPhone01Icon as SmartphoneIcon,
  SourceCodeIcon as CodeIcon,
  WhatsappIcon,
  WhatsappBusinessIcon,
  Copy01Icon as CopyIcon,
  Link01Icon as LinkIcon,
  Calendar03Icon as CalendarIcon,
  BookOpen01Icon as BookIcon,
  Tag01Icon as TagIcon,
  Globe02Icon as GlobeIcon,
  RocketIcon,
  Image01Icon as ImageIcon,
  VideoReplayIcon as VideoIcon,
  HandshakeIcon,
} from "@hugeicons/core-free-icons";

export type { IconSvgElement } from "@hugeicons/react";
