import type { Metadata } from "next";
import Link from "next/link";
import { HeroBackground } from "@/components/HeroBackground";
import { Reveal } from "@/components/Reveal";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms for working with ${siteConfig.name} — SEO, websites, apps and growth services.`,
};

export default function TermsPage() {
  return (
    <section className="relative isolate overflow-hidden bg-white pb-20 pt-16 sm:pt-20">
      <HeroBackground />
      <div className="container relative z-10 max-w-3xl">
        <Reveal className="flex flex-col gap-5">
          <span className="eyebrow">Legal</span>
          <h1 className="font-display text-4xl font-semibold tracking-tight text-ink">
            Terms of Service
          </h1>
          <p className="text-sm text-slate-500">Last updated: 24 July 2026</p>
        </Reveal>

        <div className="mt-10 space-y-8 text-slate-700">
          <p className="text-sm leading-relaxed">
            By hiring {siteConfig.name} or using this website, you agree to
            these terms. Detailed project scopes are confirmed in writing
            (WhatsApp, email or contract) before work starts.
          </p>

          <div>
            <h2 className="font-display text-xl font-semibold text-ink">
              Services
            </h2>
            <p className="mt-3 text-sm leading-relaxed">
              We provide digital marketing, SEO, website and app development,
              and related growth services for local businesses. Scope, pricing
              and deliverables are agreed per engagement.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl font-semibold text-ink">
              Pricing &amp; commitment
            </h2>
            <ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-relaxed">
              <li>No setup fee on standard plans unless otherwise agreed.</li>
              <li>
                Fixed SEO plans and Growth Partnerships have a{" "}
                <strong>6-month minimum</strong>. There is no “cancel anytime”
                option during that period.
              </li>
              <li>
                Growth Partnership commission is typically{" "}
                <strong>10% of bookings</strong> generated by our work, as
                defined in your agreement.
              </li>
              <li>
                Paid ads spend is funded by you. We may manage campaigns; we do
                not charge a separate ads management fee unless agreed in
                writing.
              </li>
            </ul>
          </div>

          <div>
            <h2 className="font-display text-xl font-semibold text-ink">
              Results
            </h2>
            <p className="mt-3 text-sm leading-relaxed">
              SEO and marketing outcomes depend on competition, your market and
              how quickly assets can be published. We work for measurable
              progress; we do not guarantee specific rankings or booking volumes
              unless a written guarantee says otherwise.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl font-semibold text-ink">
              Contact
            </h2>
            <p className="mt-3 text-sm leading-relaxed">
              <a
                href={`mailto:${siteConfig.email}`}
                className="font-semibold text-brand-500"
              >
                {siteConfig.email}
              </a>{" "}
              ·{" "}
              <Link href="/privacy" className="font-semibold text-brand-500">
                Privacy Policy
              </Link>
              <br />
              {siteConfig.addressLine}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
