/** Target cities for industry landing pages (UK + USA). Expand toward ~100+. */

export type City = {
  slug: string;
  name: string;
  country: "UK" | "USA";
  region?: string;
};

export const cities: City[] = [
  // ——— United Kingdom ———
  { slug: "london", name: "London", country: "UK", region: "England" },
  { slug: "manchester", name: "Manchester", country: "UK", region: "England" },
  { slug: "birmingham", name: "Birmingham", country: "UK", region: "England" },
  { slug: "leeds", name: "Leeds", country: "UK", region: "England" },
  { slug: "glasgow", name: "Glasgow", country: "UK", region: "Scotland" },
  { slug: "liverpool", name: "Liverpool", country: "UK", region: "England" },
  { slug: "bristol", name: "Bristol", country: "UK", region: "England" },
  { slug: "sheffield", name: "Sheffield", country: "UK", region: "England" },
  { slug: "edinburgh", name: "Edinburgh", country: "UK", region: "Scotland" },
  { slug: "cardiff", name: "Cardiff", country: "UK", region: "Wales" },
  { slug: "newcastle", name: "Newcastle", country: "UK", region: "England" },
  { slug: "nottingham", name: "Nottingham", country: "UK", region: "England" },
  { slug: "leicester", name: "Leicester", country: "UK", region: "England" },
  { slug: "coventry", name: "Coventry", country: "UK", region: "England" },
  { slug: "belfast", name: "Belfast", country: "UK", region: "Northern Ireland" },
  { slug: "brighton", name: "Brighton", country: "UK", region: "England" },
  { slug: "southampton", name: "Southampton", country: "UK", region: "England" },
  { slug: "portsmouth", name: "Portsmouth", country: "UK", region: "England" },
  { slug: "reading", name: "Reading", country: "UK", region: "England" },
  { slug: "milton-keynes", name: "Milton Keynes", country: "UK", region: "England" },
  { slug: "oxford", name: "Oxford", country: "UK", region: "England" },
  { slug: "cambridge", name: "Cambridge", country: "UK", region: "England" },
  { slug: "york", name: "York", country: "UK", region: "England" },
  { slug: "derby", name: "Derby", country: "UK", region: "England" },
  { slug: "stoke-on-trent", name: "Stoke-on-Trent", country: "UK", region: "England" },
  { slug: "wolverhampton", name: "Wolverhampton", country: "UK", region: "England" },
  { slug: "plymouth", name: "Plymouth", country: "UK", region: "England" },
  { slug: "kingston-upon-hull", name: "Hull", country: "UK", region: "England" },
  { slug: "preston", name: "Preston", country: "UK", region: "England" },
  { slug: "bradford", name: "Bradford", country: "UK", region: "England" },
  { slug: "sunderland", name: "Sunderland", country: "UK", region: "England" },
  { slug: "aberdeen", name: "Aberdeen", country: "UK", region: "Scotland" },
  { slug: "dundee", name: "Dundee", country: "UK", region: "Scotland" },
  { slug: "swansea", name: "Swansea", country: "UK", region: "Wales" },
  { slug: "newport", name: "Newport", country: "UK", region: "Wales" },
  { slug: "bournemouth", name: "Bournemouth", country: "UK", region: "England" },
  { slug: "norwich", name: "Norwich", country: "UK", region: "England" },
  { slug: "exeter", name: "Exeter", country: "UK", region: "England" },
  { slug: "cheltenham", name: "Cheltenham", country: "UK", region: "England" },
  { slug: "bath", name: "Bath", country: "UK", region: "England" },
  { slug: "ipswich", name: "Ipswich", country: "UK", region: "England" },
  { slug: "luton", name: "Luton", country: "UK", region: "England" },
  { slug: "slough", name: "Slough", country: "UK", region: "England" },
  { slug: "watford", name: "Watford", country: "UK", region: "England" },
  { slug: "croydon", name: "Croydon", country: "UK", region: "England" },
  { slug: "warrington", name: "Warrington", country: "UK", region: "England" },
  { slug: "middlesbrough", name: "Middlesbrough", country: "UK", region: "England" },
  { slug: "blackpool", name: "Blackpool", country: "UK", region: "England" },
  { slug: "bolton", name: "Bolton", country: "UK", region: "England" },
  { slug: "oldham", name: "Oldham", country: "UK", region: "England" },

  // ——— United States ———
  { slug: "new-york", name: "New York", country: "USA", region: "NY" },
  { slug: "los-angeles", name: "Los Angeles", country: "USA", region: "CA" },
  { slug: "chicago", name: "Chicago", country: "USA", region: "IL" },
  { slug: "houston", name: "Houston", country: "USA", region: "TX" },
  { slug: "phoenix", name: "Phoenix", country: "USA", region: "AZ" },
  { slug: "philadelphia", name: "Philadelphia", country: "USA", region: "PA" },
  { slug: "san-antonio", name: "San Antonio", country: "USA", region: "TX" },
  { slug: "san-diego", name: "San Diego", country: "USA", region: "CA" },
  { slug: "dallas", name: "Dallas", country: "USA", region: "TX" },
  { slug: "san-jose", name: "San Jose", country: "USA", region: "CA" },
  { slug: "austin", name: "Austin", country: "USA", region: "TX" },
  { slug: "jacksonville", name: "Jacksonville", country: "USA", region: "FL" },
  { slug: "fort-worth", name: "Fort Worth", country: "USA", region: "TX" },
  { slug: "columbus", name: "Columbus", country: "USA", region: "OH" },
  { slug: "charlotte", name: "Charlotte", country: "USA", region: "NC" },
  { slug: "san-francisco", name: "San Francisco", country: "USA", region: "CA" },
  { slug: "indianapolis", name: "Indianapolis", country: "USA", region: "IN" },
  { slug: "seattle", name: "Seattle", country: "USA", region: "WA" },
  { slug: "denver", name: "Denver", country: "USA", region: "CO" },
  { slug: "washington-dc", name: "Washington DC", country: "USA", region: "DC" },
  { slug: "boston", name: "Boston", country: "USA", region: "MA" },
  { slug: "el-paso", name: "El Paso", country: "USA", region: "TX" },
  { slug: "nashville", name: "Nashville", country: "USA", region: "TN" },
  { slug: "detroit", name: "Detroit", country: "USA", region: "MI" },
  { slug: "oklahoma-city", name: "Oklahoma City", country: "USA", region: "OK" },
  { slug: "portland", name: "Portland", country: "USA", region: "OR" },
  { slug: "las-vegas", name: "Las Vegas", country: "USA", region: "NV" },
  { slug: "memphis", name: "Memphis", country: "USA", region: "TN" },
  { slug: "louisville", name: "Louisville", country: "USA", region: "KY" },
  { slug: "baltimore", name: "Baltimore", country: "USA", region: "MD" },
  { slug: "milwaukee", name: "Milwaukee", country: "USA", region: "WI" },
  { slug: "albuquerque", name: "Albuquerque", country: "USA", region: "NM" },
  { slug: "tucson", name: "Tucson", country: "USA", region: "AZ" },
  { slug: "fresno", name: "Fresno", country: "USA", region: "CA" },
  { slug: "sacramento", name: "Sacramento", country: "USA", region: "CA" },
  { slug: "mesa", name: "Mesa", country: "USA", region: "AZ" },
  { slug: "kansas-city", name: "Kansas City", country: "USA", region: "MO" },
  { slug: "atlanta", name: "Atlanta", country: "USA", region: "GA" },
  { slug: "miami", name: "Miami", country: "USA", region: "FL" },
  { slug: "orlando", name: "Orlando", country: "USA", region: "FL" },
  { slug: "tampa", name: "Tampa", country: "USA", region: "FL" },
  { slug: "minneapolis", name: "Minneapolis", country: "USA", region: "MN" },
  { slug: "cleveland", name: "Cleveland", country: "USA", region: "OH" },
  { slug: "raleigh", name: "Raleigh", country: "USA", region: "NC" },
  { slug: "virginia-beach", name: "Virginia Beach", country: "USA", region: "VA" },
  { slug: "omaha", name: "Omaha", country: "USA", region: "NE" },
  { slug: "oakland", name: "Oakland", country: "USA", region: "CA" },
  { slug: "tulsa", name: "Tulsa", country: "USA", region: "OK" },
  { slug: "arlington", name: "Arlington", country: "USA", region: "TX" },
  { slug: "new-orleans", name: "New Orleans", country: "USA", region: "LA" },
];

export function getCity(slug: string) {
  return cities.find((c) => c.slug === slug);
}

export function citiesByCountry(country: City["country"]) {
  return cities.filter((c) => c.country === country);
}
