export type Currency = {
  code: string;
  name: string;
  /** ISO 3166-1 alpha-2 country code (lowercase) for flag image */
  flag: string;
};

/**
 * Curated list of world currencies with a representative country flag.
 * Base currency for all prices on the site is GBP.
 */
export const currencies: Currency[] = [
  { code: "GBP", name: "British Pound", flag: "gb" },
  { code: "USD", name: "US Dollar", flag: "us" },
  { code: "EUR", name: "Euro", flag: "eu" },
  { code: "AED", name: "UAE Dirham", flag: "ae" },
  { code: "AFN", name: "Afghan Afghani", flag: "af" },
  { code: "ALL", name: "Albanian Lek", flag: "al" },
  { code: "AMD", name: "Armenian Dram", flag: "am" },
  { code: "AOA", name: "Angolan Kwanza", flag: "ao" },
  { code: "ARS", name: "Argentine Peso", flag: "ar" },
  { code: "AUD", name: "Australian Dollar", flag: "au" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "az" },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", flag: "ba" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "bd" },
  { code: "BGN", name: "Bulgarian Lev", flag: "bg" },
  { code: "BHD", name: "Bahraini Dinar", flag: "bh" },
  { code: "BND", name: "Brunei Dollar", flag: "bn" },
  { code: "BOB", name: "Bolivian Boliviano", flag: "bo" },
  { code: "BRL", name: "Brazilian Real", flag: "br" },
  { code: "BWP", name: "Botswanan Pula", flag: "bw" },
  { code: "BYN", name: "Belarusian Ruble", flag: "by" },
  { code: "CAD", name: "Canadian Dollar", flag: "ca" },
  { code: "CHF", name: "Swiss Franc", flag: "ch" },
  { code: "CLP", name: "Chilean Peso", flag: "cl" },
  { code: "CNY", name: "Chinese Yuan", flag: "cn" },
  { code: "COP", name: "Colombian Peso", flag: "co" },
  { code: "CRC", name: "Costa Rican Colón", flag: "cr" },
  { code: "CZK", name: "Czech Koruna", flag: "cz" },
  { code: "DKK", name: "Danish Krone", flag: "dk" },
  { code: "DOP", name: "Dominican Peso", flag: "do" },
  { code: "DZD", name: "Algerian Dinar", flag: "dz" },
  { code: "EGP", name: "Egyptian Pound", flag: "eg" },
  { code: "ETB", name: "Ethiopian Birr", flag: "et" },
  { code: "GEL", name: "Georgian Lari", flag: "ge" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "gh" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "hk" },
  { code: "HUF", name: "Hungarian Forint", flag: "hu" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "id" },
  { code: "ILS", name: "Israeli New Shekel", flag: "il" },
  { code: "INR", name: "Indian Rupee", flag: "in" },
  { code: "IQD", name: "Iraqi Dinar", flag: "iq" },
  { code: "IRR", name: "Iranian Rial", flag: "ir" },
  { code: "ISK", name: "Icelandic Króna", flag: "is" },
  { code: "JMD", name: "Jamaican Dollar", flag: "jm" },
  { code: "JOD", name: "Jordanian Dinar", flag: "jo" },
  { code: "JPY", name: "Japanese Yen", flag: "jp" },
  { code: "KES", name: "Kenyan Shilling", flag: "ke" },
  { code: "KHR", name: "Cambodian Riel", flag: "kh" },
  { code: "KRW", name: "South Korean Won", flag: "kr" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "kw" },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "kz" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "lk" },
  { code: "MAD", name: "Moroccan Dirham", flag: "ma" },
  { code: "MDL", name: "Moldovan Leu", flag: "md" },
  { code: "MKD", name: "Macedonian Denar", flag: "mk" },
  { code: "MMK", name: "Myanmar Kyat", flag: "mm" },
  { code: "MUR", name: "Mauritian Rupee", flag: "mu" },
  { code: "MXN", name: "Mexican Peso", flag: "mx" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "my" },
  { code: "NGN", name: "Nigerian Naira", flag: "ng" },
  { code: "NOK", name: "Norwegian Krone", flag: "no" },
  { code: "NPR", name: "Nepalese Rupee", flag: "np" },
  { code: "NZD", name: "New Zealand Dollar", flag: "nz" },
  { code: "OMR", name: "Omani Rial", flag: "om" },
  { code: "PEN", name: "Peruvian Sol", flag: "pe" },
  { code: "PHP", name: "Philippine Peso", flag: "ph" },
  { code: "PKR", name: "Pakistani Rupee", flag: "pk" },
  { code: "PLN", name: "Polish Złoty", flag: "pl" },
  { code: "QAR", name: "Qatari Riyal", flag: "qa" },
  { code: "RON", name: "Romanian Leu", flag: "ro" },
  { code: "RSD", name: "Serbian Dinar", flag: "rs" },
  { code: "RUB", name: "Russian Ruble", flag: "ru" },
  { code: "SAR", name: "Saudi Riyal", flag: "sa" },
  { code: "SEK", name: "Swedish Krona", flag: "se" },
  { code: "SGD", name: "Singapore Dollar", flag: "sg" },
  { code: "THB", name: "Thai Baht", flag: "th" },
  { code: "TND", name: "Tunisian Dinar", flag: "tn" },
  { code: "TRY", name: "Turkish Lira", flag: "tr" },
  { code: "TWD", name: "New Taiwan Dollar", flag: "tw" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "tz" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "ua" },
  { code: "UGX", name: "Ugandan Shilling", flag: "ug" },
  { code: "UYU", name: "Uruguayan Peso", flag: "uy" },
  { code: "UZS", name: "Uzbekistani Som", flag: "uz" },
  { code: "VND", name: "Vietnamese Dong", flag: "vn" },
  { code: "XAF", name: "Central African CFA Franc", flag: "cm" },
  { code: "XOF", name: "West African CFA Franc", flag: "sn" },
  { code: "ZAR", name: "South African Rand", flag: "za" },
  { code: "ZMW", name: "Zambian Kwacha", flag: "zm" },
];

export const currencyMap: Record<string, Currency> = Object.fromEntries(
  currencies.map((c) => [c.code, c]),
);

/**
 * Approximate GBP-based exchange rates used as an offline fallback when the
 * live rates API is unavailable. Live rates override these when fetched.
 */
export const fallbackRates: Record<string, number> = {
  GBP: 1,
  USD: 1.27,
  EUR: 1.17,
  AED: 4.66,
  AFN: 90,
  ALL: 118,
  AMD: 490,
  AOA: 1150,
  ARS: 1250,
  AUD: 1.92,
  AZN: 2.16,
  BAM: 2.29,
  BDT: 150,
  BGN: 2.29,
  BHD: 0.48,
  BND: 1.71,
  BOB: 8.8,
  BRL: 7.2,
  BWP: 17.3,
  BYN: 4.15,
  CAD: 1.74,
  CHF: 1.12,
  CLP: 1200,
  CNY: 9.2,
  COP: 5300,
  CRC: 650,
  CZK: 29.5,
  DKK: 8.72,
  DOP: 76,
  DZD: 170,
  EGP: 62,
  ETB: 150,
  GEL: 3.45,
  GHS: 19,
  HKD: 9.9,
  HUF: 460,
  IDR: 20500,
  ILS: 4.7,
  INR: 106,
  IQD: 1660,
  IRR: 53000,
  ISK: 176,
  JMD: 200,
  JOD: 0.9,
  JPY: 190,
  KES: 164,
  KHR: 5100,
  KRW: 1750,
  KWD: 0.39,
  KZT: 600,
  LKR: 380,
  MAD: 12.6,
  MDL: 22.5,
  MKD: 72,
  MMK: 2660,
  MUR: 58,
  MXN: 23,
  MYR: 5.7,
  NGN: 1950,
  NOK: 13.7,
  NPR: 170,
  NZD: 2.1,
  OMR: 0.49,
  PEN: 4.8,
  PHP: 74,
  PKR: 353,
  PLN: 5.0,
  QAR: 4.62,
  RON: 5.8,
  RSD: 137,
  RUB: 120,
  SAR: 4.76,
  SEK: 13.5,
  SGD: 1.71,
  THB: 45,
  TND: 3.95,
  TRY: 43,
  TWD: 41,
  TZS: 3300,
  UAH: 52,
  UGX: 4800,
  UYU: 52,
  UZS: 16000,
  VND: 32000,
  XAF: 766,
  XOF: 766,
  ZAR: 23,
  ZMW: 33,
};

export const RATES_ENDPOINT = "https://open.er-api.com/v6/latest/GBP";
